import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { askJobQuestion } from '@/lib/ai';
import { useLocale, t } from '@/lib/i18n';
import type { JobQuestionAnswer } from '@/types/jobs';

export function JobQa({ jobId }: { jobId: string }) {
  const [locale] = useLocale(); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState<JobQuestionAnswer | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [count, setCount] = useState(0);
  const ask = async () => { if (!question.trim() || count >= 2 || loading) return; setLoading(true); setError(null); const result = await askJobQuestion(jobId, locale, question.trim(), count); if (result.error) setError(result.error.message); else if (result.data) { setAnswer(result.data); setCount((value) => value + 1); setQuestion(''); } setLoading(false); };
  const limited = count >= 2;
  return <View style={styles.card}><Text style={styles.heading}>{t(locale, 'ai.askQuestion')}</Text><Text style={styles.counter}>{limited ? t(locale, 'ai.limitReached') : `${count}/2`}</Text><TextInput editable={!limited && !loading} value={question} onChangeText={setQuestion} placeholder={t(locale, 'ai.questionPlaceholder')} maxLength={300} style={styles.input} multiline /><Pressable disabled={limited || loading || !question.trim()} onPress={() => void ask()} style={[styles.button, (limited || loading || !question.trim()) && styles.disabled]}><Text style={styles.buttonText}>{loading ? t(locale, 'loading.ai') : t(locale, 'ai.ask')}</Text></Pressable>{error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{answer && <View style={styles.answer}><Text style={styles.answerLabel}>{answer.notSpecified ? t(locale, 'ai.unknown') : answer.answer}</Text></View>}</View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: '#fff', borderRadius: 18, padding: 18, marginTop: 16, borderWidth: 1, borderColor: '#e6e1da' }, heading: { color: '#173b35', fontWeight: '800', fontSize: 20 }, counter: { color: '#53645f', marginTop: 6 }, input: { minHeight: 72, marginTop: 12, borderWidth: 1, borderColor: '#d8d2c9', borderRadius: 12, padding: 12, textAlignVertical: 'top' }, button: { alignSelf: 'flex-start', backgroundColor: '#173b35', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 11, marginTop: 10 }, disabled: { opacity: 0.45 }, buttonText: { color: '#fff', fontWeight: '800' }, error: { color: '#a33d2b', marginTop: 10 }, answer: { marginTop: 16, backgroundColor: '#f7f5f0', borderRadius: 12, padding: 12 }, answerLabel: { color: '#53645f', fontWeight: '700' }, answerText: { color: '#173b35', lineHeight: 21, marginTop: 6 } });
