import { useEffect, useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';

import { AiExplanation } from '@/components/jobs/ai-explanation';
import { JobQa } from '@/components/jobs/job-qa';
import { useAuth } from '@/hooks/use-auth';
import { explainJob } from '@/lib/ai';
import { addFavorite, getFavoriteForJob, removeFavorite } from '@/lib/favorites';
import { getJob } from '@/lib/jobs';
import { resetJobDetailState, type JobDetailState } from '@/lib/job-detail-state';
import { useLocale, t } from '@/lib/i18n';
import type { FavoriteJob } from '@/types/jobs';

export default function JobDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const routeId = String(id); const router = useRouter(); const [locale] = useLocale(); const auth = useAuth();
  const [state, setState] = useState<JobDetailState>({ job: null, explanation: null, loading: true, aiLoading: false, error: null, aiError: null }); const [loadedId, setLoadedId] = useState(routeId); const [favorite, setFavorite] = useState<FavoriteJob | null>(null); const [favoriteJobId, setFavoriteJobId] = useState<string | null>(null); const [favoriteBusy, setFavoriteBusy] = useState(false); const [favoriteError, setFavoriteError] = useState<string | null>(null);
  const activeState = loadedId === routeId ? state : resetJobDetailState(state); const { job, explanation, loading, aiLoading, error, aiError } = activeState;
  useEffect(() => { let mounted = true; void (async () => { const result = await getJob(routeId); if (!mounted) return; setLoadedId(routeId); if (result.error || !result.data) setState((current) => ({ ...current, loading: false, error: result.error?.message ?? t(locale, 'errors.jobNotFound') })); else { setState((current) => ({ ...current, job: result.data, aiLoading: true, loading: false, error: null, aiError: null, explanation: null })); const ai = await explainJob(result.data.id, locale); if (mounted) setState((current) => ({ ...current, explanation: ai.data, aiError: ai.error?.message ?? null, aiLoading: false })); } })(); return () => { mounted = false; }; }, [routeId, locale]);
  useEffect(() => { if (!auth.session || !job) return; let mounted = true; void getFavoriteForJob(job.id).then((result) => { if (mounted) { setFavoriteJobId(job.id); setFavorite(result.data); setFavoriteError(result.error?.message ?? null); } }); return () => { mounted = false; }; }, [auth.session, job]);
  const activeFavorite = auth.session && favoriteJobId === job?.id ? favorite : null;
  const toggleFavorite = async () => {
    if (!job || favoriteBusy) return;
    if (!auth.session) { router.push({ pathname: '/auth', params: { returnTo: `/job/${job.id}`, pendingAction: 'save', jobId: job.id } }); return; }
    const previous = activeFavorite; setFavoriteJobId(job.id); setFavoriteBusy(true); setFavoriteError(null);
    if (activeFavorite) { setFavorite(null); const result = await removeFavorite(job.id); if (result.error) { setFavorite(previous); setFavoriteError(result.error.message); } }
    else { const optimistic = { id: `optimistic-${job.id}`, userId: auth.session.user.id, jobId: job.id, createdAt: new Date().toISOString(), job }; setFavorite(optimistic); const result = await addFavorite(job.id); if (result.error) { setFavorite(previous); setFavoriteError(result.error.message); } else setFavorite(result.data ?? optimistic); }
    setFavoriteBusy(false);
  };
  if (loading) return <State text={t(locale, 'loading.jobDetails')} />; if (error || !job) return <State text={error ?? t(locale, 'errors.jobNotFound')} back={() => router.back()} />;
  return <ScrollView style={styles.safe} contentContainerStyle={styles.content}><Pressable accessibilityRole="button" accessibilityLabel={t(locale, 'actions.back')} onPress={() => router.back()}><Text style={styles.back}>‹ {t(locale, 'actions.back')}</Text></Pressable><View style={styles.titleRow}><View style={styles.titleCopy}><Text style={styles.title}>{job.title}</Text><Text style={styles.company}>{job.company}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={activeFavorite ? t(locale, 'actions.saved') : t(locale, 'actions.save')} accessibilityState={{ selected: Boolean(activeFavorite), disabled: favoriteBusy }} disabled={favoriteBusy} onPress={() => void toggleFavorite()} style={[styles.save, activeFavorite && styles.saved]}><Text style={styles.saveText}>{activeFavorite ? '✓ ' : ''}{activeFavorite ? t(locale, 'actions.saved') : t(locale, 'actions.save')}</Text></Pressable></View>{favoriteError && <Text accessibilityRole="alert" style={styles.error}>{favoriteError}</Text>}<Text style={styles.meta}>{job.city}, {job.country} · {job.jobType} · {job.level}</Text><View style={styles.source}><Text style={styles.sourceText}>{job.sourceName}</Text><Text style={styles.updated}>{t(locale, 'job.lastUpdated')}: {new Date(job.updatedAt).toLocaleDateString(locale === 'de' ? 'de-DE' : 'en-GB')}</Text></View><Text style={styles.heading}>{t(locale, 'job.description')}</Text><Text style={styles.body}>{job.rawDescription || t(locale, 'ai.unknown')}</Text><Text style={styles.heading}>{t(locale, 'job.requirements')}</Text>{job.requirements.length ? job.requirements.map((item) => <Text key={item} style={styles.bullet}>• {item}</Text>) : <Text style={styles.body}>{t(locale, 'ai.unknown')}</Text>}<View style={styles.links}>{job.applicationUrl && <Pressable accessibilityRole="link" onPress={() => void Linking.openURL(job.applicationUrl!)} style={styles.apply}><Text style={styles.applyText}>{t(locale, 'actions.apply')}</Text></Pressable>}{job.sourceUrl && <Pressable accessibilityRole="link" onPress={() => void Linking.openURL(job.sourceUrl!)}><Text style={styles.sourceLink}>{t(locale, 'job.openSource')}</Text></Pressable>}</View><AiExplanation explanation={explanation} loading={aiLoading} error={aiError} /><JobQa jobId={job.id} /></ScrollView>;
}
function State({ text, back }: { text: string; back?: () => void }) { return <View style={styles.state}><Text accessibilityRole="alert" style={styles.body}>{text}</Text>{back && <Pressable accessibilityRole="button" onPress={back}><Text style={styles.sourceLink}>Back</Text></Pressable>}</View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f7f5f0' }, content: { maxWidth: 900, width: '100%', alignSelf: 'center', padding: 20, paddingBottom: 100 }, back: { color: '#d95d39', fontWeight: '800', marginBottom: 18 }, titleRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' }, titleCopy: { flex: 1 }, title: { color: '#173b35', fontSize: 30, lineHeight: 36, fontWeight: '800' }, company: { color: '#53645f', fontSize: 18, fontWeight: '700', marginTop: 7 }, save: { backgroundColor: '#d95d39', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 }, saved: { backgroundColor: '#173b35' }, saveText: { color: '#fff', fontWeight: '800' }, error: { color: '#b33e2e', marginTop: 10 }, meta: { color: '#53645f', marginTop: 8 }, source: { backgroundColor: '#e9f1ed', borderRadius: 14, padding: 14, marginTop: 18 }, sourceText: { color: '#173b35', fontWeight: '800' }, updated: { color: '#53645f', marginTop: 5 }, heading: { color: '#173b35', fontWeight: '800', fontSize: 19, marginTop: 22 }, body: { color: '#36534b', lineHeight: 22, marginTop: 9 }, bullet: { color: '#36534b', lineHeight: 22, marginTop: 6 }, links: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, alignItems: 'center', marginTop: 22 }, apply: { backgroundColor: '#d95d39', borderRadius: 10, paddingHorizontal: 15, paddingVertical: 11 }, applyText: { color: '#fff', fontWeight: '800' }, sourceLink: { color: '#d95d39', fontWeight: '800', paddingVertical: 10 }, state: { flex: 1, backgroundColor: '#f7f5f0', alignItems: 'center', justifyContent: 'center', padding: 24 } });
