import { useEffect, useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AiExplanation } from '@/components/jobs/ai-explanation';
import { JobQa } from '@/components/jobs/job-qa';
import { explainJob } from '@/lib/ai';
import { getJob } from '@/lib/jobs';
import { useLocale, t } from '@/lib/i18n';
import type { Job, JobExplanation } from '@/types/jobs';

export default function JobDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const [locale] = useLocale(); const [job, setJob] = useState<Job | null>(null); const [explanation, setExplanation] = useState<JobExplanation | null>(null); const [loading, setLoading] = useState(true); const [aiLoading, setAiLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [aiError, setAiError] = useState<string | null>(null);
  useEffect(() => { let mounted = true; void (async () => { setLoading(true); const result = await getJob(String(id)); if (!mounted) return; if (result.error || !result.data) setError(result.error?.message ?? t(locale, 'errors.jobNotFound')); else { setJob(result.data); setAiLoading(true); const ai = await explainJob(result.data.id, locale); if (mounted) { setExplanation(ai.data); setAiError(ai.error?.message ?? null); setAiLoading(false); } } setLoading(false); })(); return () => { mounted = false; }; }, [id, locale]);
  if (loading) return <State text={t(locale, 'loading.jobDetails')} />; if (error || !job) return <State text={error ?? t(locale, 'errors.jobNotFound')} back={() => router.back()} />;
  return <ScrollView style={styles.safe} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ {t(locale, 'actions.back')}</Text></Pressable><Text style={styles.title}>{job.title}</Text><Text style={styles.company}>{job.company}</Text><Text style={styles.meta}>{job.city}, {job.country} · {job.jobType} · {job.level}</Text><View style={styles.source}><Text style={styles.sourceText}>{job.sourceName}</Text><Text style={styles.updated}>{t(locale, 'job.lastUpdated')}: {new Date(job.updatedAt).toLocaleDateString(locale === 'de' ? 'de-DE' : 'en-GB')}</Text></View><Text style={styles.heading}>{t(locale, 'job.description')}</Text><Text style={styles.body}>{job.rawDescription || t(locale, 'ai.unknown')}</Text><Text style={styles.heading}>{t(locale, 'job.requirements')}</Text>{job.requirements.length ? job.requirements.map((item) => <Text key={item} style={styles.bullet}>• {item}</Text>) : <Text style={styles.body}>{t(locale, 'ai.unknown')}</Text>}<View style={styles.links}>{job.applicationUrl && <Pressable onPress={() => void Linking.openURL(job.applicationUrl!)} style={styles.apply}><Text style={styles.applyText}>{t(locale, 'actions.apply')}</Text></Pressable>}{job.sourceUrl && <Pressable onPress={() => void Linking.openURL(job.sourceUrl!)}><Text style={styles.sourceLink}>{t(locale, 'job.openSource')}</Text></Pressable>}</View><AiExplanation explanation={explanation} loading={aiLoading} error={aiError} /><JobQa jobId={job.id} /></ScrollView>;
}
function State({ text, back }: { text: string; back?: () => void }) { return <View style={styles.state}><Text accessibilityRole="alert" style={styles.body}>{text}</Text>{back && <Pressable onPress={back}><Text style={styles.sourceLink}>Back</Text></Pressable>}</View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f7f5f0' }, content: { maxWidth: 900, width: '100%', alignSelf: 'center', padding: 20, paddingBottom: 100 }, back: { color: '#d95d39', fontWeight: '800', marginBottom: 18 }, title: { color: '#173b35', fontSize: 30, lineHeight: 36, fontWeight: '800' }, company: { color: '#53645f', fontSize: 18, fontWeight: '700', marginTop: 7 }, meta: { color: '#53645f', marginTop: 8 }, source: { backgroundColor: '#e9f1ed', borderRadius: 14, padding: 14, marginTop: 18 }, sourceText: { color: '#173b35', fontWeight: '800' }, updated: { color: '#53645f', marginTop: 5 }, heading: { color: '#173b35', fontWeight: '800', fontSize: 19, marginTop: 22 }, body: { color: '#36534b', lineHeight: 22, marginTop: 9 }, bullet: { color: '#36534b', lineHeight: 22, marginTop: 6 }, links: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, alignItems: 'center', marginTop: 22 }, apply: { backgroundColor: '#d95d39', borderRadius: 10, paddingHorizontal: 15, paddingVertical: 11 }, applyText: { color: '#fff', fontWeight: '800' }, sourceLink: { color: '#d95d39', fontWeight: '800', paddingVertical: 10 }, state: { flex: 1, backgroundColor: '#f7f5f0', alignItems: 'center', justifyContent: 'center', padding: 24 } });
